### ISSUE TITLE
Color codes appear in books and Quill

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1493]
**Description of issue or feature request:**

---

When editting books, random color codes appear although player has not entered colors nor has the permission to make colored books.
See video for a better view of the behavior https://file.io/ci41kq

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
none
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
default, so:
```
Chat:
  Colors:
    CleanUp:
      books: false
```
But even when `books: true` is the result the same

---

**Cmi Version (using`/cmi version`):** 
8.5.1.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2 build 553
**Relevant plugins (Delete if this isn't needed):** 
CMI 8.5.1.1 default config on a blank test server with minimum plugins

**Comment by Zrips** [comment]
Video link is not working, so its hard to say whats exactly is going on

**Comment by Royster0** [comment]
I can confirm that this is a bug. I have seen written books on my server which dont remove the color codes.

**Comment by x1p** [comment]
Just for everyone's information. The video was show in the discord. Zrips saw the video and is investigating as far as I know

**Comment by Momshroom** [comment]
I'm having the same issue.  No video, but here are screenshots of a book being made and the result:
[Book as it looks when the player is writing it.](http://prntscr.com/nt415p)
[The same book after the player has hit done but not signed it. ](http://prntscr.com/nt42ap)
[The same book after it's been signed.](http://prntscr.com/nt42lj)
This is on:
 -------------------------------------------------- 
CMI plugin version: 8.6.3.2 
Server version: Paper(624) 1.13.2-R0.1-SNAPSHOT 
Vault version: 1.7.2-b107 
--------------------------------------------------

**Comment by Momshroom** [comment]
This error is still present in CMI version 8.6.5.0.
The color codes appear when a return is used.   If you just use space to get to the next line, no color codes appear.  I hope that helps.

**Comment by Zrips** [comment]
Should be fixed and working correctly with latest build.

**Comment by Momshroom** [comment]
It's not fixed yet in the newest version:
https://prnt.sc/p2y28p
Every time you hit done on the book it adds &0 everywhere there's a return character.

**Comment by LogGits** [comment]
A player on my server was able to reproduce this.

**Comment by Momshroom** [comment]
This can be fixed by giving players the permissions cmi.colors.books and cmi.colors.books.black

It shouldn't need a special permission to use the default color, but it does and this fixes it :)

**Comment by Momshroom** [comment]
Actually, you also need to give cmi.colors.books.reset or you get an &r at the end when you sign it.

**Comment by ScuroK** [comment]
still having messed up books on 8.6.17.3 please reopen @Zrips

**Comment by LogGits** [comment]
I wasn't able to reproduce this on version 8.6.20.3. Can someone please let me know if this is still happening. If so, what version of CMI, Sever (and type - e.g. Paper 1.13.2 build 44). Thanks.

**Comment by x1p** [comment]
I wasn't able to reproduce it anymore.
I think we can close this one
