### ISSUE TITLE
Aliaseditor broke my commands :( 

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#155]
since the last update, my alias commands no longer work.

I've created commands for / livemap / forum / website and they have not been functional since the last update

**Comment by Zrips** [comment]
Can you give me example of one command which doesn't work? I did tested out with multiple variations, but it seems i missed something obvious.

**Comment by HomeLandingsDE** [comment]
All commands that go from the console:

Here, for example:

TeamSpeak:
   - 'fromConsole! cmi msg! [playername] &a[&6Teamspeak&a]&f:&b&lHomeLandings.de&f - To verify you, write &l/link &fin the chat'


and so (with the command structure) I did all the others too

**Comment by HomeLandingsDE** [comment]
So if I enter in the game /teamspeak - is said in the console - the player received the message but the player himself says "there is no Command by this name please inform the administrator"

**Comment by Zrips** [comment]
Ok, reproduced, should be fixed and new version will be posted in next couple hours.

**Comment by HomeLandingsDE** [comment]
Even after updating, nothing has changed so far - the commands still do not work.



25.03 12:54:44 [Server] INFO Dragilein82 issued server command: /regeln
25.03 12:54:44 [Server] INFO Es gibt keinen Befehl mit diesem Namen!
25.03 12:54:52 [Server] INFO Dragilein82 issued server command: /teamspeak
25.03 12:54:52 [Server] INFO Es gibt keinen Befehl mit diesem Namen!
25.03 12:55:00 [Server] INFO Dragilein82 issued server command: /help

**Comment by Zrips** [comment]
Well first of your command structure are... weird...
! is out of place, it should look like
**fromConsole! cmi msg [playername] !&a[&6Teamspeak&a]&f:&b&lHomeLandings.de&f - To verify you, write &l/link &fin the chat**

**Comment by HomeLandingsDE** [comment]
oki now it works but you should change the text in the wiki :)
![cmi](https://user-images.githubusercontent.com/36611372/37876196-54cd0aac-3049-11e8-805c-a1d153db9b8d.JPG)


LG Vesemir

**Comment by Zrips** [comment]
Shut... My bad.
