### ISSUE TITLE
BungeeCord Error

### ISSUE THREAD

**Issue by Drynael** [Zrips/CMI#1944]
This error pops up for connected Players randomly after connecting every 2-5 minutes

Latest CMI Version without this issue was CMI8.6.4.2.jar

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:40:51 WARN]: [CMI] Plugin CMI v8.6.5.1 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.13.2.jar:git-Paper-631]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.onPluginMessageReceived(BungeeCordAPI.java:451) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-631]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-631]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.13.2.jar:git-Paper-631]
```

---

[19:45:36 INFO]: CMI plugin version: 8.6.5.1 BungeeCord
[19:45:36 INFO]: Server version: Paper(631) 1.13.2-R0.1-SNAPSHOT
[19:45:36 INFO]: Vault version: 1.7.2-b107(CMIEInjector)
BungeeCord-Bootstrap:1.14-SNAPSHOT:8eb5683:1414

**Comment by ThisIsIPat** [comment]
Same here

**Comment by Drynael** [comment]
[10:08:36 WARN]: [CMI] Plugin CMI v8.6.5.5 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.13.2.jar:git-Paper-631]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.onPluginMessageReceived(BungeeCordAPI.java:453) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-631]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-631]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.13.2.jar:git-Paper-631]
... 14 more

[10:09:13 INFO]: CMI plugin version: 8.6.5.5 BungeeCord -> 8.6.6.0
[10:09:13 INFO]: Server version: Paper(631) 1.13.2-R0.1-SNAPSHOT
[10:09:13 INFO]: Vault version: 1.7.2-b107(CMIEInjector)

**Comment by InvertMC** [comment]
I keep getting this too. It only started happening after I updated the plugin. Makes the plugin kind of unusable with the console spam

`> [15:03:24] [Server thread/WARN]: [CMI] Plugin CMI v8.6.5.5 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[server.jar:git-Spigot-093165d-ba575a5]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.onPluginMessageReceived(BungeeCordAPI.java:453) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2491) ~[server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [server.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [server.jar:git-Spigot-093165d-ba575a5]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[server.jar:git-Spigot-093165d-ba575a5]
... 16 more`

**Comment by Drynael** [comment]
```
[17:11:22 WARN]: [CMI] Plugin CMI v8.6.6.1 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.13.2.jar:git-Paper-631]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.onPluginMessageReceived(BungeeCordAPI.java:453) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-631]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-631]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-631]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.13.2.jar:git-Paper-631]
... 14 more
```
[19:47:28 INFO]: CMI plugin version: 8.6.6.1 BungeeCord
[19:47:28 INFO]: Server version: Paper(631) 1.13.2-R0.1-SNAPSHOT
[19:47:28 INFO]: Vault version: 1.7.2-b107(CMIEInjector)
Same with Waterfall:
[19:49:05 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287 by md_5

**Comment by Drynael** [comment]
I did update my Network to 1.14.3. 
Still getting the same error:

```java
[21:30:16 WARN]: [CMI] Plugin CMI v8.6.7.1 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.14.3.jar:git-Paper-128]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.onPluginMessageReceived(BungeeCordAPI.java:453) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2683) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-128]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-128]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.14.3.jar:git-Paper-128]
... 16 more
```
CMI: 8.6.7.1
Server: Paper 1.14.3-R0.1-SNAPSHOT
Vault: 1.7.2 -b107(CMIEInjector)

**Comment by Zrips** [comment]
Should no longer be the issue with new bungee handling system
