### ISSUE TITLE
[1.15.1 Support/bug?] Many commands show 'red' (even though they work)

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2595]
**Description of issue or feature request:**
A lot of players are showing they can not get the suggestion or tab complete for `/home`, while other players say it works for them. Sometimes it's a mix between groups. Variety of custom alias commands that worked in 1.13.2 as tab complete, suggestion, etc. now show red as well. 

I've always had these 2 permissions for the default group in the groupmanager, and wasn't an issue before the upgrade from 1.13.2 to 1.15.1 and latest version of cmi. I went through `config.yml` and other files but can't figure this one out. 
```
    - cmi.command.home
    - cmi.command.homes
```

---

Note please that they CAN use /home and /somecustomalias, it just shows in red.

---

**Cmi Version (using`/cmi version`):** 
```
>cmi version
[11:56:08] [Server thread/INFO]: --------------------------------------------------
[11:56:08] [Server thread/INFO]: CMI plugin version: 8.6.16.4
[11:56:08] [Server thread/INFO]: Server version: Spigot 1.15.1-R0.1-SNAPSHOT
[11:56:08] [Server thread/INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[11:56:08] [Server thread/INFO]: --------------------------------------------------
>
```

**Server Type (Spigot/Paperspigot/etc):**  Spigot 1.15.1 (made myself, on the same system, using latest download of buildtools.jar)

**Server Version (using `/ver`):** 
```
>ver
[11:56:38] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-492a779-83af86d (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[11:56:38] [Server thread/INFO]: Checking version, please wait...
[11:56:39] [Thread-61/INFO]: You are running the latest version
>
```

**Relevant plugins (Delete if this isn't needed):** 
```
>pl
[11:56:48] [Server thread/INFO]: Plugins : WorldEdit, PlaceholderAPI, GroupManager, WorldBorder, ProtocolLib, DeathMessagesPrime, AsyncWorldEdit, MobFarmManager, AntiFire, Vault, ServerListPlus, BottledExp, HeadDatabase, LWC, WorldGuard, Citizens, AuctionHouse, TradeMe, BossShopPro, BentoBox, AdvancedAchievements, Multiverse-Core, Multiverse-Inventories, ShopChest, ItemJoin, CMI
>
```

**Comment by mrfloris** [comment]
<img width="342" alt="Screenshot 2019-12-28 at 12 00 29" src="https://user-images.githubusercontent.com/28841349/71542689-a7b23380-2969-11ea-8903-6935f1d886c0.png">
<img width="464" alt="Screenshot 2019-12-28 at 11 59 27" src="https://user-images.githubusercontent.com/28841349/71542692-b00a6e80-2969-11ea-905c-9f590d3efd22.png">
<img width="393" alt="Screenshot 2019-12-28 at 11 59 45" src="https://user-images.githubusercontent.com/28841349/71542694-b3055f00-2969-11ea-8b2a-8e4859540e33.png">
<img width="263" alt="Screenshot 2019-12-28 at 12 01 24" src="https://user-images.githubusercontent.com/28841349/71542702-c6b0c580-2969-11ea-94e3-2d478acfed88.png">

Alias.yml has /home and /homes set to true, spigot.yml has tabcomplete set to 0, so should complete all commands, /cmi home shows to tab complete properly, but /home and /homes doesn't work for example. The player can still run the command and it will execute and work, it just shows red.

**Comment by Zrips** [comment]
Interesting, cant really reproduce this one at this point. In general tab completes will be updated after player relogs, if he got access to that command with permission plugin and dint relog. This is some what new behavior from tab complete side and base command completes are updated on players login event, after that it's not updated.

**Comment by mrfloris** [comment]
Anything I can do to help debug this?

**Comment by Zrips** [comment]
Maybe get a player which has those tabcomplete broken, then ask for him to relog. And maybe investigate if he got access to that command after he logged into game and not before it.

**Comment by mrfloris** [comment]
<img width="492" alt="Screenshot 2019-12-28 at 17 20 45" src="https://user-images.githubusercontent.com/28841349/71546393-acd9a780-2996-11ea-83b5-688505ced9bb.png">
<img width="409" alt="Screenshot 2019-12-28 at 17 20 57" src="https://user-images.githubusercontent.com/28841349/71546395-ad723e00-2996-11ea-8e5f-046a8dde89cd.png">

I can set the perm to the group of players, and restart the server, it is there, but i can't check if they have it, because once they have it, it says they dont have permission to checkperm. So i can't check if they have home and homes, as operator i can check.. but the home also works as operator, so no juice there.

I can't use /cmi checkperm as an operator on another user, it only takes a keyword, not a playername, 

when it doesn't work for a user  and we log out and log back in, it still doesn't work. 

<img width="899" alt="Screenshot 2019-12-28 at 17 24 30" src="https://user-images.githubusercontent.com/28841349/71546425-f88c5100-2996-11ea-8886-c8ba4526350e.png">

Sucks that you can't reproduce it, probably means something else is happening on my end and i can't figure out what. 

on discord in msg, other people asked me the same thing last week, and told me today this happens on a few accounts on their server as well. works for one person, not for another. So I dont believe i am really isolated issue though.

**Comment by mrfloris** [comment]
I have struggled with myself and went to sleep, woke up and redid a few things just to double check.

I can let a regular player properly use /cmi checkperm now.

They cannot use /home (shows red) but pressing enter, it executes the command correctly. So they can at least use it.

/cmi checkperm home, as that player, shows they have green homes/home, ..

<img width="466" alt="Screenshot 2019-12-29 at 03 16 09" src="https://user-images.githubusercontent.com/28841349/71551513-c5bf7880-29e9-11ea-9640-546896a5a0e0.png">

and when they log out and reconnect, and type /hom.. to get to /home or /homes, it still shows red:

<img width="549" alt="Screenshot 2019-12-29 at 03 18 06" src="https://user-images.githubusercontent.com/28841349/71551516-d7088500-29e9-11ea-9dc0-b026f5991a3f.png">

**Comment by Zrips** [comment]
You are using groupmanager plugin? Its still alive? Cool, was my main choice for permission plugin back in the day, tho it had some major performance issues, maybe its fixed. Tho its besides the point. I'm testing with LuckPerms which seems to have best compatibility in all situations. maybe this is the difference between our settup which causes this issue.

**Comment by mrfloris** [comment]
Currently using this build; https://www.spigotmc.org/resources/groupmanager.38875/

Yeah, we will eventually move to LP, but for this server it really is not needed to be honest. LP will just add 90% more than I need and the same in size/mem footprint. 

I hope it's not caused by groupmanager to be honest.

**Comment by mrfloris** [comment]
Doing a dirty quick test with LP makes the problem go away. 
Removing all the plugins minus groupmanager, doesn't make it go away.
Removing groupmanager and moving it to permissions.yml, makes it go away.

I think I am convinced the issue is with groupmanager, and that it's time i am forced for this config to finally also move this server to LP (ugh). 

Closing this - despite that this Only has issues with CMI commands, and no other plugins .. i think it's an issue with the permission manager.

**Comment by mrfloris** [comment]
Sigh, I thought it was fixed, it's not.

Same setup, using luckperm, .. started showing up red again even with luckperm
<img width="311" alt="Screenshot 2020-01-15 at 08 00 34" src="https://user-images.githubusercontent.com/28841349/72412374-79a46000-376d-11ea-800a-1135e53bb2de.png">
<img width="434" alt="Screenshot 2020-01-15 at 08 00 40" src="https://user-images.githubusercontent.com/28841349/72412375-79a46000-376d-11ea-8a8d-c41d623b07e1.png">
<img width="457" alt="Screenshot 2020-01-15 at 08 00 53" src="https://user-images.githubusercontent.com/28841349/72412376-79a46000-376d-11ea-8fa3-91ca70b681f4.png">
<img width="477" alt="Screenshot 2020-01-15 at 08 01 02" src="https://user-images.githubusercontent.com/28841349/72412377-7a3cf680-376d-11ea-9900-f79c32b60c95.png">

**Comment by Sikatsu** [comment]
I'm also having this issue with luckperms, so doubt it's related to groupmanager (is that still alive?)

**Comment by mrfloris** [comment]
If the server has JUST luckperm and cmi, and vault, it seems to usually be okay. but a restart could turn it red.

**Comment by mrfloris** [comment]
Still haven't been able to fix this. :(

**Comment by Relaxing9** [comment]
Try to go to Minecraft -> Options -> Chat Settings -> Command Suggestions to True, I believe some of your players have it set to false, so it may not display as an actual command, but still execute as one.

**Comment by mrfloris** [comment]
> Try to go to Minecraft -> Options -> Chat Settings -> Command Suggestions to True, I believe some of your players have it set to false, so it may not display as an actual command, but still execute as one.

Why is it only a handful of programs, but not the other 500+ ?

It already is set to on. 

<img width="966" alt="Screenshot 2020-01-17 at 10 36 45" src="https://user-images.githubusercontent.com/28841349/72601219-44d30d00-3915-11ea-8109-52da32ff9c85.png">

**Comment by Zrips** [comment]
Should be fixed with next version.

**Comment by mrfloris** [comment]
Note: 
Spigot + Luckperms
Paper + Luckperms
Seems to work right now with a test build. 
GroupManager does not work with either. Just an FYI. 

I hate converting from one permission plugin to another. so much time testing everything just because players willllll abuse things.

**Comment by GabrielTK** [comment]
I am still experiencing this issue on Spigot + LuckPerms. Do you guys have any recommended course of action to solve this issue? CMI is updated to its latest version.

**Comment by mrfloris** [comment]
I have removed as many plugins that CMI can replace, and use LuckPerms, and magically it started working. I have no idea what the reason is to make it work.
