### ISSUE TITLE
Spawners spawning mobs during afk

### ISSUE THREAD

**Issue by SwitcherInfinityMC** [Zrips/CMI#3284]
**Description of issue:**
I've set disabling of spawning mobs from spawner on cmi config 
and disables some but not all spawners, any vanilla based (even ones picked up with silktouch and replaced) spawners still spawn regardless, but other ones dont.
---
https://pastebin.com/NSSGnpYY or
 PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
   Enabled: true
   Natural: false
   Spawners: true
   VillageDefence: true
  DisableExpPickup: true
---
**Cmi Version:**  8.6.24.2 (same thing happens on 8.6.24.0 and .1)

**Server Type:**  Paper

**Server Version:** 1.15.2

**Comment by Zrips** [comment]
Do you have some plugins which could control mob spawning from spawners?

**Comment by SwitcherInfinityMC** [comment]
We do not, we've let cmi handle all mob spawning from spawners since we've gotten it and haven't tried any other ones. It seems to have only started recently with the new updates

**Comment by Zrips** [comment]
Should be fixed with next version.

**Comment by SwitcherInfinityMC** [comment]
As of version 8.6.24.3 this is still an issue (I tested using my helper in afk whilst i was there in spectator, also afk, also tested on an alt whilst afk with the same results) On the left is ig spawners which don't spawn mobs whilst afk but on the right spiders and cave spiders still spawn regardless
![Cmi](https://user-images.githubusercontent.com/62494148/81522817-365ea480-938f-11ea-821b-ffb2b2fa13fc.png)
