### ISSUE TITLE
Flight glitchy on login

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#344]
Description of issue or feature request:

Our world limits for fly and gamemode are set to false, however these players do have:
cmi.worldlimit.fly.bypass 
but it seems to do nothing, 
when players logout while flying, when they login, they fall to the ground, and take no fall dmg
But then have to toggle fly off+on for flight to work.
(cant just double space, even thou they took no fall dmg)

The way we have found to fix this issue for now is giving them 
cmi.worldlimit.gamemode.bypass
**HOWEVER this is not ideal at all**

CONFIG SECTION (IGNORE IF NOT RELEVANT):
```
permissions:
- cmi.command.fly
- cmi.command.fly.safelogin
- cmi.worldlimit.fly.bypass```

Cmi Version (using`/cmi version`): 7.7.2.0
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`):  1.12.2-R0.1-SNOPSHOT

**Comment by RustyDagger** [comment]
I can confirm, this to be the case players complaining about having to toggle it off and back on again to have it work.

It seems to go into a glitchy state where its half working ( the fall damage is prevented ) but they are unable to fly ( despite fly being on ) either using /fly twice or /fly on once fixes it kind of annoying when they have the bypass perm and it should just work on login. 

It does work correctly on login if the player also has the gamemode bypass.

**Comment by MCTyler** [comment]
I always like the fact that it didn't leave a player in fly mode....Uhg, there goes another feature I liked.

**Comment by RustyDagger** [comment]
if you dont want them to stay in fly mode dont give them the bypass perm. your feature aint going no where, READ MAN READ

**Comment by MCTyler** [comment]
Missed that part.

**Comment by LogGits** [comment]
There is also a /tfly (correct me if i'm wrong), that allows you to give a player fly until they leave the server.

**Comment by Zrips** [comment]
I think this one was fixed at some point. Is it?

**Comment by RustyDagger** [comment]
No the permission still does not work correctly It still relies on the gamemode bypass permission instead of the Fly Bypass permission
