### ISSUE TITLE
CMI breaks TownyChat formatting

### ISSUE THREAD

**Issue by Blandix** [Zrips/CMI#3576]
Well, i'm using CMI 8.7.0.1 but with TownyChat chat formatting, and some chat colours breaks when jumps from one line to another. I thought it was TownyChat bug, but Towny Lead Developer LlamaDeal tested TownyChat and was fine. Then, a Towny Dev Momshroom (credits to her for this finding) tried new CMI 8.6.27.3 and 8.7.0.1 with the same TownyChat build, and the issue appeared.

With CMI 8.6.27.3
![image](https://user-images.githubusercontent.com/43183267/85909302-90a4af00-b7ef-11ea-8c78-f6cca649293c.png)

With CMI 8.7.0.1
![image](https://user-images.githubusercontent.com/43183267/85909293-85518380-b7ef-11ea-907f-0859175db7c3.png)

---

**Cmi Version (using`/cmi version`):** 8.7.0.1

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot 

**Server Version (using `/ver`):** 1.15.2 Build 371

**Relevant plugins (Delete if this isn't needed):** Towny 0.96.2.0 , TownyChat 0.72

**Comment by Momshroom** [comment]
I can confirm.   (Those pictures are from my server and test server.).  I’m
running paper 370 on both and the same version of townychat on both.

**Comment by dragontekgaming** [comment]
This is also happening in regular chat on paper 298 with CMI 8.7.0.2. I don't have TownyChat or any other Chat plugin.

**Comment by Blandix** [comment]
Fixed in the last update.

**Comment by Blandix** [comment]
It's not solved yet.

**Comment by thecenters** [comment]
I'm having this issue without Towny. Seems to be a problem for people on Badlion client specifically.

**Comment by CloudeLecaw** [comment]
This bug should be fixed since latest cmi allready

**Comment by Zrips** [comment]
Should be resolved by now

**Comment by Blandix** [comment]
@Zrips is not fixed

Cmi version 8.7.0.9

![image](https://user-images.githubusercontent.com/43183267/86552100-62c11800-bf1d-11ea-9924-1879121aac85.png)
![image](https://user-images.githubusercontent.com/43183267/86552111-694f8f80-bf1d-11ea-8949-2dbec6e517bf.png)
