### ISSUE TITLE
CMI 1.16.1 Error with its translation file.

### ISSUE THREAD

**Issue by Zacky26** [Zrips/CMI#3648]
**Description of issue:**
The texts aren't showing up for certain things... here are several commands which has no message.
---
Issue Pictures:
https://i.badlion.net/qky2TCwktskhYRWDA4JZH8.png
https://i.badlion.net/dE4Mqjqj9A9H3tR2Xte5Sg.png
https://i.badlion.net/Zbfkseua8RwDvFix8M5kzS.png

**Cmi Version (using`/cmi version`):** https://i.badlion.net/W5wkFsDhEn7CvhxHcxpm3N.png

**Comment by Zrips** [comment]
Update to latest version, this should be resolved with it.

**Comment by Zacky26** [comment]
Welp, I have the latest CMI and I also deleted the translations files to allow it to be rebuilt but for some reason nothing is changed... It's still broken.
