### ISSUE TITLE
/back and /home to locations in the nether sometimes puts the player on the nether roof

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#3761]
**Description of issue:**
Players doing /back and /home to locations in the nether are sometimes put on the nether roof.   These players are NOT being teleported back down by the function that should teleport players off the roof and they ARE nearly instantly killed by the void damage setting, making going /home or /back to the nether a very risky prospect.   Can safe teleport please be made not to teleport players to the nether roof?

Thank you :)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  # Will teleport players down from nether 'roof'
  PreventPlayersOnNetherRoof: true

```

---

**Cmi Version (using`/cmi version`):** 
> cmi version
[21:25:59 INFO]: --------------------------------------------------
[21:25:59 INFO]: CMI plugin version: 8.7.2.5 MySQL-> 8.7.2.6
[21:25:59 INFO]: Server: Paper(92) 1.16.1-R0.1-SNAPSHOT
[21:25:59 INFO]: CMI economy: False Vault: 1.7.2-b107 CMI Chat: False 
[21:25:59 INFO]: Modules -> 43 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[21:25:59 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 

[21:26:44 INFO]: This server is running Paper version git-Paper-92 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[21:26:44 INFO]: Checking version, please wait...
[21:26:45 INFO]: Previous version: git-Paper-89 (MC: 1.16.1)
[21:26:45 INFO]: You are 6 version(s) behind

**Comment by Zrips** [comment]
Should be resolved with next build

**Comment by Momshroom** [comment]
Thx for the improvement, but this is still happening in CMI 8.7.3.4 when players are very close to the ceiling in the nether:
https://www.youtube.com/watch?v=6WjMhr2_P0M

**Comment by Momshroom** [comment]
Please note that while I am close to the ceiling there, I'm not that close to the roof. (You can see my coordinates on my mini-map display and I'm at about 106. My nether roof is at 128.

**Comment by radiant-ai** [comment]
My 2 players just died cause they were tped to the roof on /home where they get void damage
