### ISSUE TITLE
Skin problems are persisting

### ISSUE THREAD

**Issue by WarmasterCain55** [Zrips/CMI#380]
Description of issue or feature request:

This is my 2nd attempt.  Summary is as follows.

When our server was first updated to 7.7.2.0, i tested out the skin design on me, my alt and another player.  Since then, the skins are stuck and cannot be unloaded.  Spammed /cmi skin off so many times and /cmi skin off WarmasterCain55 on me and the affected players and nothing words.  It was suggested to empty essentials skin cache and that worked at first but the skins that it changed to after it loaded in became the one stuck.

With the new version out, the resetdbfields command never works, (there's even a separate bug report from another player) and the 'skin' patch didn't do anything.  A username change was attempted, that didn't work.  When i first load in, i can see my skin briefly shows before the glitched skin loads in.

http://prntscr.com/jhilg6 - On the affected server.

http://prntscr.com/jhill4 - on another server.

If you want to talk to the owner, i can point you to him.  I believe you two have already talked before.  Name is Zombiemold.

Cmi Version (using/cmi version): 7.7.6
Server Type (Spigot/Paperspigot/etc): Paper 1.12-r0.1 snapshot
Server Version (using /ver): 1.12

**Comment by Zrips** [comment]
@WarmasterCain55 simplest way would be to disable all plugins except CMI and check it if /cmi skin off doesn't work, if its does, then something else effects your skin. And double check your config file, as by default turning off skin will set it to skin attached to that user name from Mojang servers and not to steve. You could try changing SteveOnOff to true and then set skin off.

**Comment by LogGits** [comment]
I am assuming this was resolved. If not please reopen an issue.

**Comment by WarmasterCain55** [comment]
I'm afraid it's not fixed up yet.  He's not willing to disable all the plugins but I'm going to try and have him do the /cmi resetdbfields Skin as mentioned previously.
