### ISSUE TITLE
Per rank progress value not working

### ISSUE THREAD

**Issue by TABmk** [Zrips/CMI#4215]
**Description of issue:**

![](https://cdn.discordapp.com/attachments/744698034100895868/755549160064680006/unknown.png)

Placeholders are wrong too.

Even if i set rank or add only one dafault and 2 extra, or update second it still show same % for all ranks. 

---

**CONFIG SECTION:**
#### ranks.yml
```
1:
  Enabled: true
  DisplayName: '1'
  DefaultRank: true
  StatsRequirements:
  - "ChestOpen:20"
  Commands:
  - "cmi give [playerName] stone"
2:
  Enabled: true
  DisplayName: '2'
  DefaultRank: true
  StatsRequirements:
  - "MonsterKills:slime:5"
  Commands:
  - "cmi give [playerName] stone"
```

---

**Cmi Version (using`/cmi version`):** 8.7.7.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper build 196

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by TABmk** [comment]
Still not working on 8.7.7.2

![](https://media.discordapp.net/attachments/744698034100895868/755816527927705720/unknown.png?width=1402&height=936)

**Comment by So1embum** [comment]
i'm also having this issue.. it's also not counting netherite armor under itemcrafts

**Comment by TABmk** [comment]
Still not working on 8.8.3.6

![](https://sun9-50.userapi.com/impg/3WhKnZpGVzvl_F06XwdMIufUbo39K-DXbSc6oA/2QRtIXW3XuU.jpg?size=1209x557&quality=96&sign=1108d4ea23ad7d33c1b25656e8ee94c9&type=album)

**Comment by TABmk** [comment]
@Zrips can you re-open issue, please?
