### ISSUE TITLE
Portal to Bungee server spam with warnings

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#4354]
Hello,
I have console spammed with a warning, it happens when I use a portal to change server through bungee; I tried using cmi bungee server management and command from another plugin (both portals in the config section).

If I go back to the server or if I disable the portal, the spam stops.
---
```
####################
[CMI] Plugin CMI v8.7.8.2 generated an exception while executing task 22067
java.lang.NullPointerException: null
    at com.Zrips.CMI.NBT.v1_15_R1.playEffect(v1_15_R1.java:1863) ~[?:?]
    at com.Zrips.CMI.NBT.v1_15_R1.playEffect(v1_15_R1.java:1828) ~[?:?]
    at com.Zrips.CMI.Modules.Portals.PortalManager.showParticlesForPortal(PortalManager.java:172) ~[?:?]
    at com.Zrips.CMI.Modules.Portals.PortalManager.access$3(PortalManager.java:101) ~[?:?]
    at com.Zrips.CMI.Modules.Portals.PortalManager$1$1.run(PortalManager.java:93) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-385]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-385]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-385]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]
####################
```
#####################################
Lobby:
  PvP2Hub:
    Loc: 4.0:114.0:7.0:6.0:120.0:7.0
    enabled: true
    effect: Cloud
    showParticles: true
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 10
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: false
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - asPlayer! Hub
  test:
    Loc: 8.0:114.0:3.0:8.0:117.0:3.0
    enabled: true
    effect: Reddust
    showParticles: true
    bungeeServer: Hub
    exactBungeeLocation: false
    kickBack: false
    particlesByPermission: false
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 10
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: false
    commands: []
#####################################
```
---

**Cmi Version (using`/cmi version`):** 
8.7.8.2
**CMI Bungee:**
1.0.0.4 
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-385 (1.15.2)
**Relevant plugins (Delete if this isn't needed):** 
myCommand (used for the commad /Hub)

**Comment by Zrips** [comment]
Should be fixed with next release

**Comment by FaMa91** [comment]
I still have that issue with the last update, sorry

[CMI] Plugin CMI v8.7.8.3 generated an exception while executing task 4350
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_15_R1.playEffect(v1_15_R1.java:1863) ~[?:?]
	at com.Zrips.CMI.NBT.v1_15_R1.playEffect(v1_15_R1.java:1828) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.showParticlesForPortal(PortalManager.java:172) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.access$3(PortalManager.java:101) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager$1$1.run(PortalManager.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-385]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-385]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
