### ISSUE TITLE
Portals and Holograms in non-default world fail

### ISSUE THREAD

**Issue by DaAwesomeP** [Zrips/CMI#4357]
**Description of issue:**

Portals and Holograms in the non-default world fail after a restart or two. I do not have MultiVerse.

Steps to reproduce (I have not tried this from scratch, but this is what started the issue):

1. Create a server with two worlds.
2. Create a hologram and portal in the default world
3. Change the default world in `server.properties`
4. You will see the error below on either the first server start or ones after that. Occasionally it will say it has loaded a not-loaded world and has recalculated the portal/hologram.
5. Even if you delete the hologram and portal config files and recreate the portals/holograms from commands in the server, they will stop working after a restart or two.
6. When the error below appears, `/cmi portals` and `/cmi holograms` don't work.

---

**ERROR:**
```
[22:27:42 ERROR]: Could not pass event WorldLoadEvent to CMI v8.7.8.3
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_265]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_265]
at com.Zrips.CMI.Modules.Worlds.CMIWorldListener.onWorldLoad(CMIWorldListener.java:40) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor372.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-220]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-220]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-220]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-220]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.createWorld(CraftServer.java:1166) ~[patched_1.16.3.jar:git-Paper-220]
at org.bukkit.Bukkit.createWorld(Bukkit.java:581) ~[patched_1.16.3.jar:git-Paper-220]
at com.plotsquared.bukkit.managers.BukkitWorldManager.handleWorldCreation(BukkitWorldManager.java:61) ~[?:?]
at com.plotsquared.bukkit.managers.BukkitWorldManager.handleWorldCreation(BukkitWorldManager.java:47) ~[?:?]
at com.plotsquared.bukkit.util.BukkitSetupUtils.setupWorld(BukkitSetupUtils.java:317) ~[?:?]
at com.plotsquared.bukkit.BukkitMain.setGenerator(BukkitMain.java:1073) ~[?:?]
at com.plotsquared.core.PlotSquared.lambda$new$1(PlotSquared.java:353) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-220]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-220]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:948) ~[patched_1.16.3.jar:git-Paper-220]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-220]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

---

**Cmi Version (using`/cmi version`):** v8.7.8.3 BungeeCord CMIB MySQL, no CMI economy, no CMI chat

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 220 1.16.3-R0.1-SNAPSHOT

**Comment by DaAwesomeP** [comment]
Oh, and the warps associated with that world don't work anymore either.

**Comment by DaAwesomeP** [comment]
Another error:
```
Cant load my_hologram hologram. (world_test2) is missing. Report this to developer and include your multiverse plugin name.
```
I am not using a multiverse plugin. This world is accessible in game just fine.

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by DaAwesomeP** [comment]
Any ideas?

**Comment by DaAwesomeP** [comment]
@Zrips please re-open this issue. Still having this problem.
