### ISSUE TITLE
WarmUps doesn't work with CustomAlias commands

### ISSUE THREAD

**Issue by thboehi** [Zrips/CMI#4656]
**Description of issue:**
https://github.com/Zrips/CMI/issues/4420

Warmups doesn't work on CustomAlias commands.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WarmUps:
  Enabled: true
  InformOnNoMove: true
  showCounterBarInfo: false
  showBossBarInfo: true
  List:
  - cmi tp :3:false:GlyphHead
  - cmi back:3:false:GlyphHead
  - cmi warp :3:false:GlyphHead
  - cmi home :3:false:GlyphHead
  - cmi spawn:3:false:GlyphHead
  - kraken:3:false:GlyphHead
  - royaume:3:false:GlyphHead
  - bicrew:3:false:GlyphHead
  - aodla:3:false:GlyphHead
  - skyshop:3:false:GlyphHead
```

---

**Cmi Version (using`/cmi version`):** 
8.7.10.8
**Server Type (Spigot/Paperspigot/etc):** 
PaperMC
**Server Version (using `/ver`):** 
1.16.4

**Comment by CloudeLecaw** [comment]
This is ninbuh its a feature request

**Comment by thomaboehi** [comment]
But it has worked for few days as I remember... On the issue I mentionned, he said that this was fixed...
![image](https://user-images.githubusercontent.com/50526337/100367804-0e6d2080-3003-11eb-9062-d3105941126b.png)

**Comment by edgar2308-dev** [comment]
It's currently 2025, and I'm still encountering the same issue. Has anyone found a solution yet?
