### ISSUE TITLE
moneyLog: duplicate entries

### ISSUE THREAD

**Issue by kikelkik** [Zrips/CMI#4961]
**Description of issue:**
moneyLog files contain duplicate entries for transactions caused by ChestShop.

Excerpt:
```
22/01/21 15:16:51 B lost -100,00 CT (1.766.544,81 CT)
22/01/21 15:16:51 B lost -100,00 CT (1.766.544,81 CT)
**22/01/21 15:16:51 A got 100,00 CT (24.819,77 CT)
22/01/21 15:16:51 A got 100,00 CT (24.819,77 CT)
22/01/21 15:16:57 A got 100,00 CT (24.919,77 CT)**
22/01/21 15:16:57 B lost -100,00 CT (1.766.444,81 CT)
22/01/21 15:16:57 B lost -100,00 CT (1.766.444,81 CT)
**22/01/21 15:16:57 A got 100,00 CT (24.919,77 CT)
22/01/21 15:17:00 A got 100,00 CT (25.019,77 CT)**
22/01/21 15:17:00 B lost -100,00 CT (1.766.344,81 CT)
22/01/21 15:17:00 B lost -100,00 CT (1.766.344,81 CT)
**22/01/21 15:17:00 A got 100,00 CT (25.019,77 CT)**
22/01/21 15:17:03 B lost -100,00 CT (1.766.244,81 CT)
**22/01/21 15:17:03 A got 100,00 CT (25.119,77 CT)**
22/01/21 15:17:03 B lost -100,00 CT (1.766.244,81 CT)
**22/01/21 15:17:03 A got 100,00 CT (25.119,77 CT)**
``` 
As you can see, entries are just duplicates (total amount of a player only changes each 2nd entry).

---

**Cmi Version (using`/cmi version`):** 8.8.0.4

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 

**Server Version (using `/ver`):** git-Paper-436 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):** ChestShop version 3.11.1-SNAPSHOT (build 265)

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by TheoRetisch1** [comment]
Could you please reopen the bug report? Unfortunately, the update didn't solve the problem. Transactions triggered by ChestShop are still logged twice :/

Paper 1.16.5 - 466
CMI version 8.8.1.1
ChestShop 3.12-SNAPSHOT (build 274)

Example:
```
13/02/21 00:00:06 Fredo023 got ,15 CT (342.134,68 CT)
13/02/21 00:00:06 Fredo023 got ,15 CT (342.134,68 CT)
13/02/21 00:01:26 Donnersteppe got 27,46 CT (430.912,30 CT)
13/02/21 00:01:26 Donnersteppe got 27,46 CT (430.912,30 CT)
13/02/21 00:01:46 Donnersteppe got 29,74 CT (430.942,04 CT)
13/02/21 00:01:46 Donnersteppe got 29,74 CT (430.942,04 CT)
13/02/21 00:02:06 Donnersteppe got 45,67 CT (430.987,71 CT)
13/02/21 00:02:06 Donnersteppe got 45,67 CT (430.987,71 CT)
13/02/21 00:03:06 Donnersteppe got 38,97 CT (431.026,68 CT)
13/02/21 00:03:06 Donnersteppe got 38,97 CT (431.026,68 CT)
13/02/21 00:03:21 Perlisander got 1.000,00 CT (138.478,31 CT)
13/02/21 00:03:26 Donnersteppe got 22,63 CT (431.049,31 CT)
13/02/21 00:03:26 Donnersteppe got 22,63 CT (431.049,31 CT)
13/02/21 00:03:46 Donnersteppe got 46,24 CT (431.095,55 CT)
13/02/21 00:03:46 Donnersteppe got 46,24 CT (431.095,55 CT)
13/02/21 00:04:06 Donnersteppe got 46,78 CT (431.142,33 CT)
13/02/21 00:04:06 Donnersteppe got 46,78 CT (431.142,33 CT)

```
