### ISSUE TITLE
Nested placeholders (parseother) still don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4990]
**Description of issue:**
Hi, I wanna report that nested placeholders still don't work, even not in /cmi placeholders parse.
`%parseother_{cmi_random_player_name}_{vault_prefix}% ` This should be the working one, but it doesn't work... It does with %% around cmi_random... but then it creates this: 
![image](https://user-images.githubusercontent.com/18662086/106044277-cd1aef00-60df-11eb-95b5-1c323f099836.png)

So there's something wrong with it
---

---

**Cmi Version (using`/cmi version`):** 8.8.0.5

**Server Type (Spigot/Paperspigot/etc):**  Yutopia

**Server Version (using `/ver`):** 1.16.5, 7 yutopia release

**Relevant plugins (Delete if this isn't needed):** Placeholderapi parseother extension

**Comment by bobhenl** [comment]
@Zrips  now please just this to combination of lastplayer & uptime and I could finally make what I need

**Comment by Zrips** [comment]
Yea, it still contained some issues relating to placeholders like that, revisited it and retested with previously reported issues, all seams to be ok now. So it should be resolved with next update.

**Comment by bobhenl** [comment]
Wait, sorry but I still can't get it work, what did you used as command? This doesn't work for me: /cmi placeholders parse %parseother_{cmi_random_player_name}_{vault_prefix}%

Neither with /cmi placeholders parse %parseother_{%cmi_random_player_name%}_{vault_prefix}%
