### ISSUE TITLE
Nested placehodlers still don't work

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5047]
**Description of issue:**

---

Hi, I would like to continue in ticket https://github.com/Zrips/CMI/issues/4990, cause it's still not solved, so if it could be reopened?

---

**Cmi Version (using`/cmi version`):** 8.8.1.0

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 1.16.5, 17

**Relevant plugins (Delete if this isn't needed):** PlaceholderAPI

**Comment by dkalaxdk** [comment]
Related to your mentioned issue, does it work, if you do not have the % at the start and end, so the command becomes:
`/placeholders parse parseother_{cmi_random_player_name}_{vault_prefix}` instead?

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/107163906-7d280c00-69ac-11eb-9243-9105cae21d0a.png)

This happens with the command you've mentioned

**Comment by dkalaxdk** [comment]
Could you translate the output please? :)

**Comment by bobhenl** [comment]
as you can see it parsed other random player DominikX and then prefix, but from some reason it used my name and my prefix, but still this can't be used in custom aliases as mentioned here https://github.com/Zrips/CMI/issues/4990

**Comment by Zrips** [comment]
This could even be issue with PAPI as of testing everything seams to work properly. When trying to parse /placeholders parse %parseother_{cmi_random_player_name}_{player_name}% getting random player name parsed by PAPI, and %parseother_{cmi_random_player_name}_{vault_prefix}% returns random player prefix

**Comment by bobhenl** [comment]
And di you try it in custom alias Zrips?

**Comment by Zrips** [comment]
Should be fixed with next build

**Comment by bobhenl** [comment]
Seems still not fixed, did you try this example? https://pastebin.com/QQpzVFgw
