### ISSUE TITLE
Random region being generated *FROM* the world player use /cmi rt (AutoGenerateWorlds: false not working.)

### ISSUE THREAD

**Issue by josephcy95** [Zrips/CMI#5596]
**Description of issue:**
Let's say there's 2 world, a spawn world where there is wolrd border set at 500x500 block radius, then there is a main survival world where world border radius set at 10000x10000, the issue I've noticed is when a player use "/cmi rt world" when he is in the spawn world, a few random region .mca file will be generated in spawn world region folder, instead of just world folder.

A small spawn region that only takes 20MB has grown into 5GB in a month because my players use /cmi rt when they first spawn in spawn world.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  AutoGenerateWorlds: false
  Worlds:
    spawn:
      Enabled: false
      MaxRange: 2
      MinRange: 1
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world:
      Enabled: true
      MaxRange: 10000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`): 8.8.4.4** 

**Server Type (Spigot/Paperspigot/etc): Tested on both Paper and Purpur** 

**Server Version (using `/ver`): Paper Build 712 and Purpur build 1126** 

**Relevant plugins (Delete if this isn't needed): Multiverse-Core**

**Comment by CloudeLecaw** [comment]
why u havent enabled it rt? if you have not enabled it then it used default values

**Comment by josephcy95** [comment]
> why u havent enabled irt for spawn? well you have rt of 2 blocks? not must but ok... not invailed^^....
> 
> and now count 1 and 1 togehter.... then you know why your world was gettig bigger.
> On teleport commands the best choose is it to generate or better load the chunks in the world you are before the player
> gets teleported. where the plugin else should know if he get stucked or not? it also could creat unwanted effects because the chunk was not loaded..
> Even if you set a worldborder arround the spawnworld this means still that the chunks try to load and maybe player also get portet there even worldborder sends them back or to the border - finaly rt is still a teleport command.
> 
> About Autogenerate false i see your comment the #once are left. you missunderstood the setting.
> you might can regenerate a little testconfig to have all #informations aggain this is often helpfull to understand the config better and faster and not to missunderstand it.
> 
> ```
>   # If this set to true we will generate random teleport default settings for all detected worlds
>   # Setting to false will not longer generate world setups, but you can add them manually if needed
>   AutoGenerateWorlds: true
> ```
> 
> if you have not enabled it then it used default values
> default are values for world or first active one in your case that is world with maxrange 10000
> 
> now you could say - but what if i set all to false... well then you better should ask yourself why you allow rt ;)
> The best setuo here is first define the default (the first active one)
> and then define the rest. Also make clear that default is allways taken when your not enabling an other definition
> 
> you tried disabling rt just for one world (the world your in right? Well you seen this is not possible. so your setup with a low min max range is correct here to work arround this missing fact that you cant disable it to certain worlds

I'm not really sure I understand what you are saying, but I have tried both AutoGenerateWorlds set to true and false, the point is not to generate random region .mca files in the world where random teleport is disabled, I disabled spawn because there's no point for use to random teleport in spawn, which I believe it's a pretty standard setup.

And believe me I know this is a bug, not a settings error, because this random world region being generated behavior happens IN THE WORLD I'm using /cmi rt, regardless which world I'm random teleporting.

If I'm now in **world** and I use **/cmi rt world** then no world region would be generated in **spawn**, but when I'm in **spawn** and I use **/cmi rt world**, it generate random region in **spawn** (What is the point of generating region in at the world which is not my target world for random teleporting? )

**Comment by CloudeLecaw** [comment]
well still with your current setting you allow rndom teleport in spawnworld in
      MaxRange: 10000
      MinRange: 500

**Comment by Zrips** [comment]
@josephcy95 
Should get resolved with next build

**Comment by josephcy95** [comment]
Hi I have tested the latest version 8.8.4.6 but this issue are still happening when using /cmi rt it still generate region files in source country instead of target
