### ISSUE TITLE
ERROR Could not pass event PlayerBedEnterEvent to CMI v9.5.0.9

### ISSUE THREAD

**Issue by danyadanya2005** [Zrips/CMI#7831]
### Description of Issue

I have an error please help me

### Version Information

```shell
[CMILib] Loading server plugin CMILib v1.2.5.3
[CMI] Loading server plugin CMI v9.5.0.9
Purpur version git-Purpur-1967 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
```

### Errors

```shell
https://pastebin.com/gqXyseq7
```

### Relevant Plugins

Vault-1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by danyadanya2005** [comment]
note that you already had this error in August 2022 https://github.com/Zrips/CMI/issues/7128

**Comment by CloudeLecaw** [comment]
yes and it was fixed there ;)

**Comment by danyadanya2005** [comment]
You can see for yourself that the error is back. unfortunately I can not reproduce the error because I don’t understand what caused it .. well, I don’t deny that Purpur-1967 may be to blame

**Comment by danyadanya2005** [comment]
I was able to reproduce the error
I have a bloodmoon-advanced plugin on my server where it is forbidden to sleep during a blood moon. this plugin does not let the player sleep. and when I press on the bed at night during the blood moon, an error is written in the console. what should I do?

**Comment by CloudeLecaw** [comment]
well i would report this to the dev of the bloodmoon plugin and ask him if there is a way for him to add compatibility

**Comment by danyadanya2005** [comment]
Another plugin's fault

**Comment by danyadanya2005** [comment]
https://www.spigotmc.org/resources/bloodmoon.74270/
as an experiment, I installed this free plugin. and I also have errors in CMI
[2023-05-13-2.log](https://github.com/Zrips/CMI/files/11471879/2023-05-13-2.log)

**Comment by CloudeLecaw** [comment]
try it without your bloodmoon plugin and report him the error.

**Comment by danyadanya2005** [comment]
I have already removed bloodmoon I will test tomorrow

**Comment by danyadanya2005** [comment]
how do you view the logs? it feels like you were watching my log with closed eyes 
this error has nothing to do with the CMI plugin ("Could not pass event EntityDeathEvent to BloodMoon v0.8.1") . CMI error CMIlib is at the end of the log ! 
[17:15:23] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to CMI v9.5.0.9
java.lang.IllegalArgumentException: advancement
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]

**Comment by danyadanya2005** [comment]
Hi I checked without "blood moon" the error is still present CMI. the blood moon has nothing to do with this error! Please fix this
[2023-05-14-3.log](https://github.com/Zrips/CMI/files/11474529/2023-05-14-3.log)

**Comment by Zrips** [comment]
@BillyGalbreath 
Can you provide locale line you are using for info.sleepersRequired line? Looks like there is issue with this particular handling or your setup of it, either way would be nice to have example which one failed to speed up this process in fixing it.

**Comment by Zrips** [comment]
Ok, should be fixed with next version of CMILib.
