### ISSUE TITLE
Signs not working correctly.

### ISSUE THREAD

**Issue by MedvedEE** [Zrips/CMI#7932]
### Description of Issue

Whenever the user right-clicks on a sign, It opens the edit menu. You can't right-click on a sign to put another on top or front. The users don't have the cmi.signs.shiftedit permission, so they should not be able to edit it.
With the first version that supported Minecraft 1.20, players could not even write text on a sign. Now it is currently fixed but can still edit. 

https://github.com/Zrips/CMI/assets/10268986/7dc84413-235f-4e17-af4a-b0666cc8da90

### Version Information

```shell
https://imgur.com/a/Lw5cSuz
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Text you change should not be saved when you close UI. This is known issue with 1.20 servers due to native sign edit support and lacking control we as developers have over it at the moment. I can prevent this UI from opening, but that basically brakes majority of sing plugins which are dependent on sign interactions, so its not really a fix. Currently you an still open UI but text you change will not be saved, which is the best thing we can do at the moment to keep other plugins working and prevent sign editing

**Comment by valenvaio** [comment]
>... Currently you an still open UI but text you change will not be saved, which is the best thing we can do at the moment to keep other plugins working and prevent sign editing

Unfortunately, this option also causes problems. In CraftBook, this leads to loss of blocks and inoperability in mechanisms like gates or bridges.
When you try to open the gate (click on the plate) at the moment of gate triggering the edit window opens, after closing the edit window the plate on the plate remains the old record (including the number of blocks), although the bridge or gate triggered and now the value of the number of blocks does not correspond to the state of the gate. After that the mechanism does not work and the gate hangs in the state open, which leads to loss of blocks.

**Comment by thenullmatrix** [comment]
I Have the same issue when trying to edit the hanging signs to add text to the other side. We never used the CMI sign editor. I wish there was an option to disable the CMI sign editor so we can just use the native UI in 1.20.x to add text to the hanging signs.

**Comment by MedvedEE** [comment]
My problems were fixed with CMI 9.6.1.1

**Comment by thenullmatrix** [comment]
> My problems were fixed with CMI 9.6.1.1

I am currently running  9.6.1.1

**Comment by Zrips** [comment]
@thenullmatrix 
Could you elaborate more on your issue here? What exactly isn't working for you and is this issue persistent across all signs or just hinging ones?

**Comment by thenullmatrix** [comment]
Just the hanging signs. The native UI just opens and closes quickly when trying to right click and add text to the other side of the sign. It works fine if I remove CMI. Since Mojang added a way to edit these signs I would rather have the option to disable the sign editing on CMI.

**Comment by mrfloris** [comment]
More changes have been made by Paper as well as CMI / CMILib, could people here please update the Paper server engine to their latest build, and CMILib/CMI as well, and see which issues have now been resolved for them potentially?

I myself have had less and less issues.

**Comment by thenullmatrix** [comment]
> More changes have been made by Paper as well as CMI / CMILib, could people here please update the Paper server engine to their latest build, and CMILib/CMI as well, and see which issues have now been resolved for them potentially?
> 
> I myself have had less and less issues.

I am currently up to date (running Spigot not paper) Editing hanging signs works when CMI is not loaded. When CMI is loaded you can not right click to edit the signs. I understand there is some issue between Spigot and CMI. all Im asking for is a way to disable the option to control sign in CMI so the two do not conflict.

**Comment by mrfloris** [comment]
Spigot doesn't have the sign fixes that paper did add. I recommend doing a /stop, and removing the spigot jar, get the paper jar, and update your shell or batch script to start up, and then start the server .. and you've upgraded. 
things will run smoother, faster, more bugs fixed, and better sign stuff. 

spigot + cmi signs won't be able to get addressed much, because spigot doesn't seem to update their API - paper has done so a few times.

**Comment by thenullmatrix** [comment]
Signs work fine on spigot Im not asking for more features. Paper is a fork of spigot plus i have some plugins that are not supported on paper but are on spigot.  Please don't assume that one fixes all over the other. All Im asking for is a better remedy than blocking the function from working all together.

**Comment by mrfloris** [comment]
If there's no api events to use by plugins, then plugins like cmi can't - if you want signs to work properly for plugins, then ask spigot to add those events. Yes, spigot works with signs just fine, without the plugins that want to extend their features. But you want cmi features to be used on signs, so you run into that issue.

**Comment by thenullmatrix** [comment]
I also will like the option to not use those features so that I can use the hanging signs in the way Mojang intended  not to have half the sign disabled. If I was running a plugin that just handled signs it would be easy to just disable that. With CMI is a whole package with many other plugins. Im not asking for it to be disabled for everyone as a hole the the option to disable that part if I choose not to use them.  It's more like requesting a feature. Zrips already has opened issues with spigot so there is no need to open duplicate tickets.

**Comment by mrfloris** [comment]
> I also will like the option to not use those features so that I can use the hanging signs in the way Mojang intended not to have half the sign disabled. If I was running a plugin that just handled signs it would be easy to just disable that. With CMI is a whole package with many other plugins. Im not asking for it to be disabled for everyone as a hole the the option to disable that part if I choose not to use them. It's more like requesting a feature. Zrips already has opened issues with spigot so there is no need to open duplicate tickets.

i said it to make a point, but I will just say "you are right" and leave the conversation instead of trying to give some courtesy info the best I can.

**Comment by Zrips** [comment]
Was resolved with latest CMI and 1.20.1 server builds.
