### ISSUE TITLE
CMI IC (Interactive Commands) asFakeOp! blocked by Plotsquared (?)

### ISSUE THREAD

**Issue by AnimeDrache** [Zrips/CMI#7950]
### Description of Issue

When you create an interactive sign of the plugin CMI, it WON'T work if you try to make it a "asFakeOP!" command (so the command thinks you are an OP). Normally it does work. It also does work "asconsole!" or "asPlayer!".

Please see the attachment here for the issue. Maybe "plotsquared" does block it!? https://prnt.sc/2z5GNUFfy2jI

### Version Information

```shell
9.6.1.1.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by SirYwell** [comment]
PlotSquared allows fake players/NPCs with version 2 UUIDs. Otherwise, it assumes it's a real player that is online.

**Comment by Zrips** [comment]
Should be resolved with next CMI build

**Comment by AnimeDrache** [comment]
Thank you! Your latest update did fix it! I still don't really understand the half of the things you said guys, but as a user I can clearly say: I can use CMI IC on plotsquared and everywhere else with fakeop command now without an error message plus it does work! ♥ Case closed hehe!
