### ISSUE TITLE
CMIAnvilItemRenameEvent and CMIAnvilItemRepairEvent experience are still deducted after being cancelled

### ISSUE THREAD

**Issue by killertuling** [Zrips/CMI#8745]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/19590076/544cafad-a390-4df8-a411-5e80eeef0723)

https://github.com/Zrips/CMI/assets/19590076/ba7f7043-e98f-4756-8bba-f17e01085eff

I used skript to monitor the CMIAnvilItemRenameEvent, but after the event was cancelled normally, the player's experience points were still deducted.

### Version Information

```shell
[19:22:59 INFO]: --------------------------------------------------
[19:22:59 INFO]: CMI 插件版本: 9.7.2.9 BungeeCord CMIB  MySQL-> 9.7.2.10
[19:22:59 INFO]: CMILib: 1.4.7.9 -> 1.4.7.11
[19:22:59 INFO]: 服务器版本: Paper(496) 1.20.4-R0.1-SNAPSHOT-
[19:22:59 INFO]: CMI 经济: Disabled 经济: 1.7.3-CMI CMI 聊天: Disabled
[19:22:59 INFO]: 模块 -> 37 已启用 22 已禁用: hpBossBar, mirror, launchPad, tablist, versionCheck, moneyCheque, jail, elytraBoost, spawners, playerChatTag, rideAnimation, elytraLaunch, durabilityLoss, kits, bossBarCompass, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, namePlates, homeInteractions
[19:22:59 INFO]: --------------------------------------------------
```

### Relevant Plugins

Skript-2.8.5、Skript-Reflect-2.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by killertuling** [comment]
> Should be fixed with next update

This bug still exists in the latest version, could you please check it again?
![image](https://github.com/Zrips/CMI/assets/19590076/0e4548bb-435f-44d5-a658-2bd4249e623b)
