### ISSUE TITLE
CMI holograms interactable problems persist 

### ISSUE THREAD

**Issue by RickyLaChow** [Zrips/CMI#8785]
### Description of Issue

@Zrips The issue persist i need to use  NewMethod: false for make it work in the new versions 

```yml
consegna_pizza_1:
  Loc: Prymacity;721.51;71.37;-197.57
  ShowParticles: false
  HoverParticles:
    ShowHover: false
  Range: 8
  RangeExtra: 10
  SpacingIcon: 1.4
  Interactable: true
  NewMethod: false
  NewDisplay: true
  ND:
    Bill: VERTICAL
    BColor: "{#Black}"
  RequiresPermission: true
  Commands:
    - asPlayer! pizzaboy consegna
  Lines:
    - " {#D8FF71}ᴄᴏɴsᴇɢɴᴀ ᴘɪᴢᴢᴀ"
    - " {#EFFFC4}ᴄʟɪᴄᴄᴀ ᴘᴇʀ ɪɴᴛᴇʀᴀɢɪʀᴇ"
```

### Version Information

```shell
[14:42:34 INFO]: --------------------------------------------------
[14:42:34 INFO]: CMI: 9.7.2.12 Velocity CMIB  SqLite
[14:42:34 INFO]: CMILib: 1.4.7.14 
[14:42:34 INFO]: Server: Paper(496) 1.20.4-R0.1-SNAPSHOT-
[14:42:34 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[14:42:34 INFO]: Modules -> 24 enabled 35 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, chatBubble, playerCombat, shulkerBackpack, cooldown, spawnerCharge, namePlates, homeInteractions, hpBossBar, launchPad, elytraExploit, portals, afk, anvilRenameColor, spawners, paintingEditor, playerChatTag, durabilityLoss, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, silentChest, warmup, totemBehavior
[14:42:34 INFO]: --------------------------------------------------
```
```


### Errors

_No response_

### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
Confirming this persists for me as well, but switching between methods does not fix it.

CMI plugin version: 9.7.2.12 Velocity CMIB  SqLite
CMILib: 1.4.7.15 
Server: Paper(497) 1.20.4-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 57 enabled 2 disabled: ranks, skin

**Comment by Zrips** [comment]
Could you try pressing F3+B to enable collision box debugging and check if you can see floating hit box when you aim at hologram like this
![image](https://github.com/Zrips/CMI/assets/10416201/c46cf9a1-d1b3-4430-b0d0-2f84342daf5d)

**Comment by ChrisTVH** [comment]
To me in purpur 1.20.4 (Purpur(2175) 1.20.4-RO.1-SNAPSHOT), the holograms in general work horrible, if you reload the cmi they duplicate, if you go far away and come back they take too long to reappear, etc.

All this happens to me with the latest version of the CMI (9.7.2.12)so far and cmilib (1.4.7.15), when did this start?

When they began to have changes in the holograms with the arrival of 1.20.5/1.20.6.

**Comment by mercurialmusic** [comment]
> To me in purpur 1.20.4 (Purpur(2175) 1.20.4-RO.1-SNAPSHOT), the holograms in general work horrible, if you reload the cmi they duplicate, if you go far away and come back they take too long to reappear, etc.
> 
> All this happens to me with the latest version of the CMI (9.7.2.12)so far and cmilib (1.4.7.15), when did this start?
> 
> When they began to have changes in the holograms with the arrival of 1.20.5/1.20.6. 

These kinds of things should be expected during update season, tbh, especially with plugins with backwards support or when you're using non-standard software. It usually takes a bit to get everything sorted so it's best to be patient and provide constructive feedback. If you're not willing to do that then staying on older versions is still an option, but just saying things are horrible doesn't help anyone.

**Comment by ChrisTVH** [comment]
> > To me in purpur 1.20.4 (Purpur(2175) 1.20.4-RO.1-SNAPSHOT), the holograms in general work horrible, if you reload the cmi they duplicate, if you go far away and come back they take too long to reappear, etc.
> > All this happens to me with the latest version of the CMI (9.7.2.12)so far and cmilib (1.4.7.15), when did this start?
> > When they began to have changes in the holograms with the arrival of 1.20.5/1.20.6.
> 
> These kinds of things should be expected during update season, tbh, especially with plugins with backwards support or when you're using non-standard software. It usually takes a bit to get everything sorted so it's best to be patient and provide constructive feedback. If you're not willing to do that then staying on older versions is still an option, but just saying things are horrible doesn't help anyone.

I apologize if my message sounded too offensive, I just want to make it clear of your functionality, as long as you are aware of it and fix it in the future I am fine.

If I am required to cooperate with more information I will be available for it.

**Comment by ChrisTVH** [comment]
Now the holograms work fine again, but there is still a small detail, clicking on the buttons to change pages is unprintable.
![image](https://github.com/Zrips/CMI/assets/58376852/93e347dc-7a51-4269-985e-c585b38ddc4d)
![image](https://github.com/Zrips/CMI/assets/58376852/b311c9cc-2a45-4c89-86db-71d25c64328c)

If you need more information do not hesitate to ask me.

**Comment by SenorFlamingo** [comment]
I've got the same issue with holograms not being interactable. Both the old and the new display method for holograms have the same issue, they don't trigger the commands that are attached to the hologram.
![image](https://github.com/Zrips/CMI/assets/53866997/969a9760-f334-46ec-b69c-fa7f8e452e93)

```
Boogschutterhighscores:
  Loc: skyblock_world;157.41;84.77;-119.54
  HoverParticles:
    ShowHover: false
  Range: 8
  RangeExtra: 16
  Interactable: true
  Commands:
  - '!rightclick!cmi hologrampages Boogschutterhighscores [playerName] next'
  - '!shiftrightclick!cmi hologrampages Boogschutterhighscores [playerName] next'
  Lines:
  - '&7---- * ----'
  - '{#orange>}&lBoogschutter Highsco{#e6b173<>}&lres Allertijden{#orange<}&r'
  - '&7---- * ----'
  - '{#orange}1 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_1_alltime_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_1_alltime_value%'
  - '{#orange}2 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_2_alltime_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_2_alltime_value%'
  - '{#orange}3 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_3_alltime_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_3_alltime_value%'
  - '{#orange}4 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_4_alltime_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_4_alltime_value%'
  - '{#orange}5 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_5_alltime_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_5_alltime_value%'
  - '&r'
  - <T>{#orange>}Meer stat{#e6b173<>}istieken{#orange<}</T><H>{#orange>}&lMeer stat{#e6b173<>}&listieken{#orange<}</H>
  - '!nextpage!'
  - '&7---- * ----'
  - '{#red>}&lBoogschutter Highsc{#e68a8a<>}&lores Wekelijks{#red<}&r'
  - '&7---- * ----'
  - '{#red}1 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_1_weekly_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_1_weekly_value%'
  - '{#red}2 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_2_weekly_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_2_weekly_value%'
  - '{#red}3 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_3_weekly_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_3_weekly_value%'
  - '{#red}4 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_4_weekly_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_4_weekly_value%'
  - '{#red}5 &8>> &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_5_weekly_name%
    &7- &f%ajlb_lb_betonquest_questeiland-archeryrange:point.highscore.amount_5_weekly_value%'
  - '&r'
  - <T>{#red>}Meer stat{#e68a8a<>}istieken{#red<}</T><H>{#red>}&lMeer stat{#e68a8a<>}&listieken{#red<}</H>
```

**Comment by ChrisTVH** [comment]
![image](https://github.com/Zrips/CMI/assets/58376852/7d7e8b8d-5db6-46f7-9a91-6b6a474aea65)

**Comment by jeffry1829** [comment]
I've got the same issue, the next page button may work or may not work sometimes.

**Comment by ChrisTVH** [comment]
This should already be fixed in the latest versions, it should be closed.

**Comment by jeffry1829** [comment]
No, the problem persists in my server, turn the page few times, then it will stop working for a while.

**Comment by ChrisTVH** [comment]
> No, the problem persists in my server, turn the page few times, then it will stop working for a while. (Player needs to point some where else to trigger the next page button)

Put the details where it happens to you, like which server version, cmi version, etc.
