### ISSUE TITLE
cmi openbook and cmi getbook issue when containing ctext

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8906]
### Description of Issue
When i use the cmi openbook command to open a book from a ctext i get a strange looking text.
The same happens when using the cmi getbook command.

lIt ooks like it prints out the whole vanilla ntb text instead of the formated ctext..
![06-07-2024_17-08-10](https://github.com/Zrips/CMI/assets/12080017/be05120a-4856-4b6d-af5e-2a8e44936f31)

### Version Information
![06-07-2024_17-08-31](https://github.com/Zrips/CMI/assets/12080017/05e28bd0-3a2f-4a34-b33d-32b0d7c9616b)

### Errors
strange ntb code in the opened book by cmi openbook command  and  cmi getbook command  if the ctext from it contain ctext.

### Relevant Config Sections
original ctext from the txt file:
```yaml
<AutoPage>
<T>&7&l❊❊❊❊❊❊❊❊❊❊❊❊❊</T>
<T>&2&l  M&c&la&2&lr&c&li&2&la&c&ls &2&lT&c&la&2&lg&c&le&2&lb&c&lu&2&lc&c&lh</T>
<T>&7&l❊❊❊❊❊❊❊❊❊❊❊❊❊</T>
<T>&6 </T>
<T>&0Liebes Tagebuch</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&6 </T>
<T>&0Vor zwei Wochen habe</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0Ich einem grünen Mann</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0von meiner wertvollen</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0Kiste erzählt,</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0welche ich in</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0meinem geheimen</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0Versteck unter &2dem</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&2Stall &0versteckt habe.</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<NextPage>
<T>&7&l❊❊❊❊❊❊❊❊❊❊❊❊❊</T>
<T>&2&l  M&c&la&2&lr&c&li&2&la&c&ls &2&lT&c&la&2&lg&c&le&2&lb&c&lu&2&lc&c&lh</T>
<T>&7&l❊❊❊❊❊❊❊❊❊❊❊❊❊</T>
<T>&6 </T>
<T>&0Ich erzählte dem Mann</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0von meiner &6Kugel&0,</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0welche ich für den</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0Zugang &2beim Stall</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0benötige..</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>benötige
<T>&0Der grüne Mann</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0grinste zufrieden</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0als er von &6der Kugel</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0hörte...</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<NextPage>
<T>&7&l❊❊❊❊❊❊❊❊❊❊❊❊❊</T>
<T>&2&l  M&c&la&2&lr&c&li&2&la&c&ls &2&lT&c&la&2&lg&c&le&2&lb&c&lu&2&lc&c&lh</T>
<T>&7&l❊❊❊❊❊❊❊❊❊❊❊❊❊</T>
<T>&6 </T>
<T>&0Hoffentlich war es</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0kein Fehler ihm davon</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0zu erzählen.</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0Sollte jemand &6die</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&6Kugel &0finden, so</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0bringt er Diese</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0hoffentliche zu mir</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&2zum Stall&0. Dann kann</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0ich ihm den Weg</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&0zum Schatz zeigen.</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&6 </T>
<NextPage>
<T>&6 </T>
<T>&7&n Info:</T>
<T>&6 </T>
<T>&7&oSolltet Du das</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&oTagebuch nicht</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&omehr besitzen, so</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&okannst Du Dir den</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&oWeg jederzeit vom</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&ovom Spawn aus mit</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&odem Befehl:&0</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&4/wegzumaria</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
<T>&7&onavigieren lassen.</T><H>&fHier klicken um vom Spawn zu Marias Stall geleitet zu werden.</H><C>/wegzumaria</C>
```

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Truongvv10** [comment]
I have the same issue persisting on my servers
![image](https://github.com/Zrips/CMI/assets/67742370/25ec83e8-9ed9-4910-83fd-93d09df04cf6)

**Comment by Ceddix** [comment]
Same happens for me. Must have been broken in one of the last versions.

**Comment by mrfloris** [comment]
I can reproduce this with my welcomeMessage .txt file from the ctext folder.
`/cmi openbook welcomeMessage`

<img width="966" alt="Screenshot 2024-07-11 at 19 09 03" src="https://github.com/Zrips/CMI/assets/28841349/aa4b16da-569d-4c8f-b5f3-17fda647c4be">

<img width="966" alt="Screenshot 2024-07-11 at 19 09 23" src="https://github.com/Zrips/CMI/assets/28841349/2addb0d1-b330-4e3e-91db-597c5671f9ac">

Same for getbook of course.
<img width="654" alt="Screenshot 2024-07-11 at 19 09 58" src="https://github.com/Zrips/CMI/assets/28841349/00283f66-e4c1-4d36-ab33-92717941b56f">

same on cmilib .7

**Comment by Ceddix** [comment]
However, I have not yet switched to 1.21 yet. My server is still on 1.20.4, and I only updated CMI yesterday.
This is the version I am currently on, and on which the problem occurs:
![image](https://github.com/Zrips/CMI/assets/49922771/3193490b-8602-4043-8808-9f81589cee66)
On one of my test servers, on 1.21 (Purpur Build `1.21-2258-ff19bcc` and same CMI and CMILib version) it does not work either.

I have tried to downgrade, and from version `9.7.4.1` it works:
![image](https://github.com/Zrips/CMI/assets/49922771/a35a46ba-de65-4052-b706-f11a178faf83)
And indeed, there were also changes to the openbook command in this version (see changelog): `Fix for openbook command not working on 1.21 servers`.

**Comment by Zrips** [comment]
Should be fixed with next version

**Comment by ScuroK** [comment]
> Should be fixed with next version

i am on paper 1.20.6 and openbook and getbook still doesnt work

**Comment by mrfloris** [comment]
exception error on 1.20.4 now.

**Comment by CloudeLecaw** [comment]
on paper 1.21 its fixed.

**Comment by mrfloris** [comment]
The next CMI build should have a fix for older servers again.
