### ISSUE TITLE
AFK kick feature not working

### ISSUE THREAD

**Issue by Achent007** [Zrips/CMI#9120]
### Description of Issue

Hello!
Since some days i have my players on the afk state but got never kicked and they have the permission `cmi.command.afk.kickOutIn.600` and on the config i have this :

### Version Information

```shell
CMI: 9.7.5.9 Unknown  MySQL
CMILib: 1.5.1.3 
Server: Paper(40) 1.21.1-R0.1-SNAPSHOT-
CMI economy: Désactivé(e) CMI Chat: Activé(e) 
Modules -> 41 enabled 25 disabled: spawnerProximity, cuffed, tablist, moneyCheque, elytraBoost, elytraLaunch, bossBarCompass, chatBubble, playerCombat, votifier, headDrop, spawnerCharge, vanish, timedCommands, launchPad, elytraExploit, jail, spawners, flightCharge, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, silentChest, totemBehavior
```

### Relevant Config Sections

```yaml
:
  Enabled: true
  TitleMessage: true
  SubTitleMessage: true
  PreventJumping: true
  PreventDamage: false
  CheckInterval: 2
  StopPlayTime: true
  AutoAfkIn: 300
  AutoAfkCmds: []
  ManualAfkCmds: []
  AfkLeaveCmds: []
  AutoKickIn: 600
  RepeatingAutoKickInterval: 600
  RepeatKickCommand: false
  AutoKickCmds:
  - cmi server Lobby-01 [playerName]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tested out with your setup, everything looks to be working correctly. Try testing this with more generic command, like sending player message or just kicking him out of the game instead of trying to send to specific bungee server in case there is issue with that command in particular

**Comment by Ergail** [comment]
Hi, resetting the afk.yml doesn't change anything, no command executed by this file is recognized. There must be a problem somewhere else that makes this module not work, despite the fact that the module is set to true... We're trying to figure it out, but we can't find the source of the problem, and given the number of options, it's a bit complicated to test!

**Comment by Ergail** [comment]
Ok, so after a lot more testing, it's because of the “vanish” module, which must be set to true because false blocks commands executed by the AFK module.

We don't use CMI's vanish but PremiumVanish, is it necessary to keep the vanish module?

**Comment by Valeoria** [comment]
I am also having this issue, no commands are triggering upon afk either. Only happened since updating a couple of versions of cmi today.

**Comment by CloudeLecaw** [comment]
Today an other player wrote his normal comamnds are not triggered too.
He usses pupur but that should be a matter in this case.
his players get afk but the commands are not triggered.

**Comment by AntiS0ul** [comment]
Having this issue as well. Using version 9.7.5.3

**Comment by Zrips** [comment]
@Ergail 
Thanks for the extensive debugging, you mentioning vanish module give me idea what's going on and it will fixed with next update.

**Comment by Valeoria** [comment]
Since todays update, all `AutoAfkCmds:`, `ManualAfkCmds:` and `AutoKickCmds:` commands are working now, but nothing from the `AfkLeaveCmds:` are working...

**Comment by CloudeLecaw** [comment]
> Since todays update, all `AutoAfkCmds:`, `ManualAfkCmds:` and `AutoKickCmds:` commands are working now, but nothing from the `AfkLeaveCmds:` are working...

ALl working if the vanished modul is enabled

So a little bug remains
